config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :pins

  root "pins#index"
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :title, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController

  before_action :find_pin, only: [:show, :edit, :update, :destroy]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC")
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: 'Pin was successfuly created.'
    else
      render :new
    end
  end

  # GET /pins/1/edit
  def edit
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfuly updated.'
    else
      render :edit, alert: @pin.errors
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy

    redirect_to pins_path
  end

  private

    def find_pin
      @pin = Pin.find(params[:id])
    end

    def pin_params
      params.require(:pin).permit(:title, :description, :image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title PinPin
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "PinPin", root_path

      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li= link_to "New Pin", new_pin_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path

  .container
    - if notice
      %p.alert.alert-info
        = notice
    - if alert
      %p.alert.alert-danger
        = alert

    = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |form|

  - if @pin.image?
    .form-group
      = image_tag @pin.image.url(:medium)

  .form-group
    = form.input :image, input_html: { class: 'form-control' }

  .form-group
    = form.input :title, input_html: { class: 'form-control' }

  .form-group
    = form.input :description, input_html: { class: 'form-control' }

  .form-actions
    = form.button :submit, class: 'btn btn-primary'

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
  %h1 Edit Form

  %div= render 'form'

  %p
    = link_to 'Cancel', @pin

app/views/pins/index.html.haml
%h1 Pins

%p
  = link_to 'new pin', new_pin_path

- @pins.each do |pin|
  %div
    = link_to image_tag(pin.image.url (:medium)), pin
    %h2= link_to pin.title, pin
    %p= pin.description

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  %h1 New FORM

  = render 'form'

  = link_to "Back", pins_path

app/views/pins/show.html.haml
.col-md-6.col-md-offset-3
  - if @pin.image?
    = image_tag @pin.image.url(:medium)

  %h1= @pin.title
  %p= @pin.description
  %p
    Posted by
    = @pin.user.email

  %p= link_to 'Edit', edit_pin_path
  %p= link_to 'Delete', @pin, method: :delete, data: { :confirm => "Are you sure?" }
  %p= link_to 'Back', pins_path